### ISSUE TITLE
Change SaveAssetPath

### ISSUE THREAD

**Issue by cbanwell** [Whinarn/UnityMeshSimplifier#45] opened 2021-03-26 15:43 UTC
Hiya, 

The asset save path seems to be hard coded to always be under UMS_LODs, regardless if the saveAssetPath is set.

If I set saveAssetPath, it just creates that path under the folder Assets/UMS_LODs.

It's also seems to remove spaces from the folder name and inject '_' s

**Comment by Whinarn** [comment] 2021-03-26 19:37
The fact that it always save the assets under `Assets/UMS_LODs/` is in fact not a bug, but perhaps a bad design choice. Changing this will break backwards compatibility, but it's perhaps fine to release a new major version of this package. I also think it's bad to restrict this in case the user has a preferred directory structure in the project.

Regarding spaces been replaces by underscores, I'm not entirely sure why that was done, except the fact that as a programmer I always avoid spaces in paths due to various bugs in applications etc. But also perhaps bad to make that decision for the user. I could look into that as well.

I'll look into this as soon as I have some time over.
Thank you for reporting this!

**Comment by Whinarn** [comment] 2021-03-26 23:14
This has now been implemented with https://github.com/Whinarn/UnityMeshSimplifier/pull/46 and released into next version.

**Closed by Whinarn** 2021-03-26 23:14 UTC
Labels: bug
